// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskActivityLogsFieldNames          = builder.RawFieldNames(&TaskActivityLogs{}, true)
	taskActivityLogsRows                = strings.Join(taskActivityLogsFieldNames, ",")
	taskActivityLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(taskActivityLogsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	taskActivityLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(taskActivityLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	taskActivityLogsModel interface {
		Insert(ctx context.Context, data *TaskActivityLogs) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TaskActivityLogs, error)
		Update(ctx context.Context, data *TaskActivityLogs) error
		Delete(ctx context.Context, id string) error
	}

	defaultTaskActivityLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaskActivityLogs struct {
		Id           string         `db:"id"`            // 主键 UUID
		TaskId       string         `db:"task_id"`       // 被修改的任务 ID
		ActorId      string         `db:"actor_id"`      // 执行操作的用户 ID
		ActionType   string         `db:"action_type"`   // 操作类型：CREATE, UPDATE, DELETE, STATUS_CHANGE
		FieldChanged sql.NullString `db:"field_changed"` // 被修改的字段名 (如 status, assignee_id)
		OldValue     sql.NullString `db:"old_value"`     // 修改前的旧值 (JSONB 格式)
		NewValue     sql.NullString `db:"new_value"`     // 修改后的新值 (JSONB 格式)
		Description  sql.NullString `db:"description"`   // 人类可读的操作描述 (如“张三修改了截止时间”)
		CreatedAt    time.Time      `db:"created_at"`    // 操作发生的时间
	}
)

func newTaskActivityLogsModel(conn sqlx.SqlConn) *defaultTaskActivityLogsModel {
	return &defaultTaskActivityLogsModel{
		conn:  conn,
		table: `"public"."task_activity_logs"`,
	}
}

func (m *defaultTaskActivityLogsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaskActivityLogsModel) FindOne(ctx context.Context, id string) (*TaskActivityLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", taskActivityLogsRows, m.table)
	var resp TaskActivityLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskActivityLogsModel) Insert(ctx context.Context, data *TaskActivityLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, taskActivityLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TaskId, data.ActorId, data.ActionType, data.FieldChanged, data.OldValue, data.NewValue, data.Description)
	return ret, err
}

func (m *defaultTaskActivityLogsModel) Update(ctx context.Context, data *TaskActivityLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, taskActivityLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.TaskId, data.ActorId, data.ActionType, data.FieldChanged, data.OldValue, data.NewValue, data.Description)
	return err
}

func (m *defaultTaskActivityLogsModel) tableName() string {
	return m.table
}
