// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBehaviorLogsFieldNames          = builder.RawFieldNames(&UserBehaviorLogs{}, true)
	userBehaviorLogsRows                = strings.Join(userBehaviorLogsFieldNames, ",")
	userBehaviorLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(userBehaviorLogsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userBehaviorLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userBehaviorLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	userBehaviorLogsModel interface {
		Insert(ctx context.Context, data *UserBehaviorLogs) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserBehaviorLogs, error)
		Update(ctx context.Context, data *UserBehaviorLogs) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserBehaviorLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserBehaviorLogs struct {
		Id          string         `db:"id"`           // 主键 UUID
		UserId      sql.NullString `db:"user_id"`      // 用户 ID (游客可能为空)
		EventType   string         `db:"event_type"`   // 事件类型：CLICK(点击), VIEW(浏览), STAY(停留)
		EventTarget sql.NullString `db:"event_target"` // 事件目标标识 (如 btn_submit, page_home)
		PageUrl     sql.NullString `db:"page_url"`     // 事件发生的页面 URL
		MetaData    sql.NullString `db:"meta_data"`    // 元数据 (JSONB)：存储停留时长、错误信息等额外参数
		CreatedAt   time.Time      `db:"created_at"`   // 事件发生时间
	}
)

func newUserBehaviorLogsModel(conn sqlx.SqlConn) *defaultUserBehaviorLogsModel {
	return &defaultUserBehaviorLogsModel{
		conn:  conn,
		table: `"public"."user_behavior_logs"`,
	}
}

func (m *defaultUserBehaviorLogsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserBehaviorLogsModel) FindOne(ctx context.Context, id string) (*UserBehaviorLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userBehaviorLogsRows, m.table)
	var resp UserBehaviorLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBehaviorLogsModel) Insert(ctx context.Context, data *UserBehaviorLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, userBehaviorLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.EventType, data.EventTarget, data.PageUrl, data.MetaData)
	return ret, err
}

func (m *defaultUserBehaviorLogsModel) Update(ctx context.Context, data *UserBehaviorLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, userBehaviorLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.EventType, data.EventTarget, data.PageUrl, data.MetaData)
	return err
}

func (m *defaultUserBehaviorLogsModel) tableName() string {
	return m.table
}
