// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLoginLogsFieldNames          = builder.RawFieldNames(&UserLoginLogs{}, true)
	userLoginLogsRows                = strings.Join(userLoginLogsFieldNames, ",")
	userLoginLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(userLoginLogsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userLoginLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userLoginLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	userLoginLogsModel interface {
		Insert(ctx context.Context, data *UserLoginLogs) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserLoginLogs, error)
		Update(ctx context.Context, data *UserLoginLogs) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserLoginLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLoginLogs struct {
		Id        string         `db:"id"`         // 主键 UUID
		UserId    string         `db:"user_id"`    // 登录的用户 ID
		IpAddress sql.NullString `db:"ip_address"` // 登录时的 IP 地址
		UserAgent sql.NullString `db:"user_agent"` // 浏览器或设备信息 (User-Agent)
		LoginAt   time.Time      `db:"login_at"`   // 登录时间
	}
)

func newUserLoginLogsModel(conn sqlx.SqlConn) *defaultUserLoginLogsModel {
	return &defaultUserLoginLogsModel{
		conn:  conn,
		table: `"public"."user_login_logs"`,
	}
}

func (m *defaultUserLoginLogsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLoginLogsModel) FindOne(ctx context.Context, id string) (*UserLoginLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userLoginLogsRows, m.table)
	var resp UserLoginLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLoginLogsModel) Insert(ctx context.Context, data *UserLoginLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, userLoginLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.IpAddress, data.UserAgent, data.LoginAt)
	return ret, err
}

func (m *defaultUserLoginLogsModel) Update(ctx context.Context, data *UserLoginLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, userLoginLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.IpAddress, data.UserAgent, data.LoginAt)
	return err
}

func (m *defaultUserLoginLogsModel) tableName() string {
	return m.table
}
